#!/usr/bin/env python3
"""Turn the OpenXR conformance suite's table of interaction profiles into Rust.

Khronos' OpenXR-CTS (Apache-2.0) generates, from the specification, a list of every interaction
profile with the component paths each has and what makes each available -- a version of OpenXR, or
extensions being enabled. A runtime has to accept a suggestion that is valid and refuse one that is
not, so this is the table `xrSuggestInteractionProfileBindings` is checked against.

    tools/gen-profile-table.py <OpenXR-CTS>/build/src/conformance/framework > \
        crates/spatiand-openxr/src/profiles_table.rs

Run it again, from a newer suite, when the specification adds a profile.
"""
import re
import sys
from pathlib import Path

root = Path(sys.argv[1])
header = (root / "interaction_info_generated.h").read_text()
source = (root / "interaction_info_generated.cpp").read_text()

# The enumerants, in order, and the availabilities they stand for, in the same order: each is a
# list of alternatives and each alternative a set of features that must all be there.
enum_body = re.search(r"enum class InteractionProfileAvailability \{(.*?)\};", header, re.S).group(1)
names = re.findall(r"Avail_(\w+)", enum_body)
array_body = re.search(r"kInteractionAvailabilities\{\{(.*)\}\};", header, re.S).group(1)
avails = []
for entry in re.findall(r"Availability\{(.*?)\}\s*\}\s*,?", array_body, re.S):
    pass
# An Availability is `Availability{ FeatureSet{ BIT_a, BIT_b, } , FeatureSet{ ... } }`.
entries = re.split(r"\n\s*Availability\{", "\n" + array_body)[1:]
for e in entries:
    sets = re.findall(r"FeatureSet\{(.*?)\}", e, re.S)
    avails.append([re.findall(r"BIT_(\w+)", s) for s in sets])
assert len(avails) == len(names), (len(avails), len(names))
index = {n: i for i, n in enumerate(names)}

# Each profile: its path, availability and component paths.
collections = {}
for m in re.finditer(r"static const BindingPathDataCollection (\w+)\{(.*?)\n    \};", source, re.S):
    items = re.findall(r'BindingPathData\{\s*"([^"]+)",\s*(\w+),\s*InteractionProfileAvailability::Avail_(\w+)', m.group(2))
    collections[m.group(1)] = items

profiles = []
for m in re.finditer(
    r'\{\s*"(/interaction_profiles/[^"]+)",\s*"[^"]*",\s*\{.*?\},\s*InteractionProfileAvailability::Avail_(\w+),\s*(c_interaction_profiles_\w+)\s*\}',
    source,
    re.S,
):
    profiles.append((m.group(1), m.group(2), collections[m.group(3)]))

types = {"XR_ACTION_TYPE_BOOLEAN_INPUT": "Bool", "XR_ACTION_TYPE_FLOAT_INPUT": "Float",
         "XR_ACTION_TYPE_VECTOR2F_INPUT": "Vec2", "XR_ACTION_TYPE_POSE_INPUT": "Pose",
         "XR_ACTION_TYPE_VIBRATION_OUTPUT": "Haptic"}

out = []
out.append("// *********** GENERATED by tools/gen-profile-table.py -- DO NOT EDIT ***********")
out.append("//")
out.append("// From the Khronos OpenXR conformance suite's interaction profile data (Apache-2.0,")
out.append("// Copyright The Khronos Group Inc.), which is itself generated from the OpenXR specification.")
out.append("")
out.append("/// What a component path carries.")
out.append("#[derive(Debug, Clone, Copy, PartialEq, Eq)]")
out.append("pub enum Kind { Bool, Float, Vec2, Pose, Haptic }")
out.append("")
out.append("/// What makes something available: any one of these sets of features, each all of its features.")
out.append("pub type Availability = &'static [&'static [&'static str]];")
out.append("")
out.append("pub struct Component { pub path: &'static str, pub kind: Kind, pub available: usize }")
out.append("pub struct Profile { pub path: &'static str, pub available: usize, pub components: &'static [Component] }")
out.append("")
out.append(f"pub static AVAILABILITIES: [Availability; {len(avails)}] = [")
for a in avails:
    alts = ", ".join("&[" + ", ".join(f'"{f}"' for f in s) + "]" for s in a)
    out.append(f"    &[{alts}],")
out.append("];")
out.append("")
out.append(f"pub static PROFILES: [Profile; {len(profiles)}] = [")
for path, avail, items in profiles:
    out.append(f'    Profile {{ path: "{path}", available: {index[avail]}, components: &[')
    for p, t, a in items:
        out.append(f'        Component {{ path: "{p}", kind: Kind::{types[t]}, available: {index[a]} }},')
    out.append("    ] },")
out.append("];")
print("\n".join(out))
